name: Publish Snapshots
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Change wrapper permissions
        run: |
          cd plugin
          chmod +x ./gradlew
      - name: Publish to SayanDevelopment snapshot repo
        run: |
          cd plugin
          ./gradlew publish
        env:
          REPO_SAYAN_USER: ${{ secrets.REPO_SAYAN_USER }}
          REPO_SAYAN_TOKEN: ${{ secrets.REPO_SAYAN_TOKEN }}